// Unified Route Registry — Single source of truth for Router, Navigation, Breadcrumbs & Search
export const ROUTE_REGISTRY = {
  HOME: { path: '/', name: 'Daily Snapshot Terminal', category: 'pipeline' },
  LANDING: { path: '/landing', name: 'PMS Engine Platform', category: 'marketing' },
  LOGIN: { path: '/login', name: 'Authentication', category: 'auth' },
  WORKSPACE: { path: '/workspace', name: 'Research Workspace', category: 'workspace' },
  DASHBOARD: { path: '/dashboard', name: 'Dashboard Signals Cache', category: 'research' },
  SEARCH: { path: '/search', name: 'Stock Search', category: 'research' },
  STOCK_DETAIL: { path: '/stock/:symbol', name: 'Stock Detail', category: 'research' },
  MARKET: { path: '/market', name: 'Market Overview', category: 'markets' },
  SECTORS: { path: '/sectors', name: 'Sector Performance', category: 'markets' },
  BREADTH: { path: '/breadth', name: 'Market Breadth', category: 'markets' },
  RATINGS: { path: '/ratings', name: 'Ratings Distribution', category: 'markets' },
  WATCHLISTS: { path: '/watchlists', name: 'Smart Watchlists', category: 'markets' },
  PORTFOLIO: { path: '/portfolio', name: 'Portfolio Allocation', category: 'research' },
  STUDIO: { path: '/studio', name: 'Quant Strategy Studio', category: 'strategies' },
  STRATEGY_VALIDATE: { path: '/strategy/:strategyId/validate', name: 'Strategy Validation', category: 'strategies' },
  BACKTEST_RESULTS: { path: '/backtest/:runId', name: 'Backtest Results', category: 'strategies' },
  BACKTEST_HISTORY: { path: '/backtest/history', name: 'Backtest History', category: 'strategies' },
  REPORTS: { path: '/reports', name: 'Research Reports', category: 'analytics' },
  CHANGES: { path: '/changes', name: 'Daily Recommendation Changes', category: 'analytics' },
  ARCHIVE: { path: '/archive', name: 'Historical Archive', category: 'analytics' },
  DATA_QUALITY: { path: '/data-quality', name: 'Data Quality & Diagnostics', category: 'pipeline' },
  SNAPSHOT_DIAGNOSTICS: { path: '/snapshot-diagnostics', name: 'Snapshot Diagnostics', category: 'pipeline' },

  // 24 Quant Laboratories
  LAB_HOME: { path: '/lab', name: 'Quant Research Laboratory', pillar: 'Overview' },
  LAB_INDICATORS: { path: '/lab/indicators', name: 'Indicator Lab', pillar: 'Market Intelligence' },
  LAB_SECTOR: { path: '/lab/sector', name: 'Sector Analysis Lab', pillar: 'Market Intelligence' },
  LAB_REGIME: { path: '/lab/regime', name: 'Market Regime Lab', pillar: 'Market Intelligence' },
  LAB_BREADTH: { path: '/lab/breadth', name: 'Market Breadth Lab', pillar: 'Market Intelligence' },
  LAB_LIQUIDITY: { path: '/lab/liquidity', name: 'Liquidity Audit Lab', pillar: 'Market Intelligence' },
  LAB_FEATURES: { path: '/lab/features', name: 'Feature Selection Lab', pillar: 'Feature Engineering' },
  LAB_CROSS_INDICATOR: { path: '/lab/cross-indicator', name: 'Cross-Indicator Lab', pillar: 'Feature Engineering' },
  LAB_MODELS: { path: '/lab/models', name: 'Model Research Lab', pillar: 'Machine Learning' },
  LAB_ENSEMBLE: { path: '/lab/ensemble', name: 'Ensemble Strategy Lab', pillar: 'Machine Learning' },
  LAB_HYPEROPT: { path: '/lab/hyperopt', name: 'Parameter Hyperopt Lab', pillar: 'Machine Learning' },
  LAB_MONTE_CARLO: { path: '/lab/monte-carlo', name: 'Monte Carlo Sandbox', pillar: 'Risk & Stress' },
  LAB_STRESS: { path: '/lab/stress', name: 'Crisis Stress Tester', pillar: 'Risk & Stress' },
  LAB_SIZING: { path: '/lab/sizing', name: 'Position Sizing Lab', pillar: 'Risk & Stress' },
  LAB_DRIFT: { path: '/lab/drift', name: 'Score Drift Monitor', pillar: 'Risk & Stress' },
  LAB_PORTFOLIO: { path: '/lab/portfolio', name: 'Portfolio Strategies', pillar: 'Portfolio Research' },
  LAB_CONSTRUCTION: { path: '/lab/construction', name: 'Portfolio Construction', pillar: 'Portfolio Research' },
  LAB_CORRELATION: { path: '/lab/correlation', name: 'Correlation Research', pillar: 'Portfolio Research' },
  LAB_BENCHMARK: { path: '/lab/benchmark', name: 'Benchmark Comparison', pillar: 'Portfolio Research' },
  LAB_ENGINE: { path: '/lab/engine', name: 'Engine Score Validation', pillar: 'Validation' },
  LAB_COMPOSITE: { path: '/lab/composite', name: 'Composite Weights Lab', pillar: 'Validation' },
  LAB_VALIDATION: { path: '/lab/validation', name: 'Recommendation Audit', pillar: 'Validation' },
  LAB_EXPERIMENTS: { path: '/lab/experiments', name: 'Experiment History', pillar: 'Registry' },
  LAB_REPORTS: { path: '/lab/reports', name: 'Quant Reports Compiler', pillar: 'Registry' },

  KNOWLEDGE: { path: '/docs', name: 'Knowledge Center', category: 'resources' }
};
