"""Initial schema migration

Revision ID: 373203f01064
Revises: 
Create Date: 2026-07-14 11:43:16.773266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373203f01064'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('analyzed_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_table('explainability_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('score_type', sa.String(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('indicator_contributions', sa.Text(), nullable=True),
    sa.Column('feature_contributions', sa.Text(), nullable=True),
    sa.Column('current_values', sa.Text(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('validation_metrics', sa.Text(), nullable=True),
    sa.Column('research_references', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'symbol', 'score_type', name='uq_explainability_snapshot_symbol_score')
    )
    op.create_table('feature_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('normalized_values', sa.Text(), nullable=True),
    sa.Column('z_scores', sa.Text(), nullable=True),
    sa.Column('rolling_statistics', sa.Text(), nullable=True),
    sa.Column('lag_features', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'symbol', name='uq_feature_snapshot_symbol')
    )
    op.create_table('indicator_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('ema20', sa.Float(), nullable=True),
    sa.Column('ema50', sa.Float(), nullable=True),
    sa.Column('ema200', sa.Float(), nullable=True),
    sa.Column('sma20', sa.Float(), nullable=True),
    sa.Column('sma50', sa.Float(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('adx', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('supertrend', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('ichimoku', sa.Text(), nullable=True),
    sa.Column('obv', sa.Float(), nullable=True),
    sa.Column('cmf', sa.Float(), nullable=True),
    sa.Column('mfi', sa.Float(), nullable=True),
    sa.Column('roc', sa.Float(), nullable=True),
    sa.Column('cci', sa.Float(), nullable=True),
    sa.Column('williams_r', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'symbol', name='uq_indicator_snapshot_symbol')
    )
    op.create_table('lab_drift_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_experiments',
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('lab_module', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('params_json', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('error_msg', sa.String(), nullable=True),
    sa.Column('reproducibility_seed', sa.Integer(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('dataset_version', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('indicator_version', sa.String(), nullable=True),
    sa.Column('pipeline_stage', sa.String(), nullable=True),
    sa.Column('is_paused', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_table('lab_rec_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.String(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('forward_return', sa.Float(), nullable=True),
    sa.Column('validated', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'horizon_days', name='uq_rec_audit_analysis_horizon')
    )
    op.create_table('lab_reports',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('generated_at', sa.String(), nullable=False),
    sa.Column('html_path', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('lab_weight_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('w_technical', sa.Float(), nullable=True),
    sa.Column('w_ml', sa.Float(), nullable=True),
    sa.Column('w_gru', sa.Float(), nullable=True),
    sa.Column('w_reliability', sa.Float(), nullable=True),
    sa.Column('target_metric', sa.String(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_daily',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('trading_date', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adjusted_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('delivery_volume', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('last_trading_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'trading_date')
    )
    op.create_table('my_stocks',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('added_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('report_history',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('generated_at', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('report_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('report_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('html_report_path', sa.String(), nullable=True),
    sa.Column('pdf_report_path', sa.String(), nullable=True),
    sa.Column('generation_timestamp', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('ensemble_score', sa.Float(), nullable=True),
    sa.Column('gru_score', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'symbol', name='uq_score_snapshot_symbol')
    )
    op.create_table('security_master',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('market_cap_category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('snapshots',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.String(), nullable=False),
    sa.Column('market_date', sa.String(), nullable=False),
    sa.Column('generated_at', sa.String(), nullable=False),
    sa.Column('is_official', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stocks_processed', sa.Integer(), nullable=True),
    sa.Column('stocks_failed', sa.Integer(), nullable=True),
    sa.Column('universe_version', sa.String(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('indicator_version', sa.String(), nullable=True),
    sa.Column('scoring_version', sa.String(), nullable=True),
    sa.Column('ml_model_version', sa.String(), nullable=True),
    sa.Column('feature_version', sa.String(), nullable=True),
    sa.Column('software_build', sa.String(), nullable=True),
    sa.Column('pipeline_started_at', sa.String(), nullable=True),
    sa.Column('pipeline_ended_at', sa.String(), nullable=True),
    sa.Column('pipeline_duration_sec', sa.Float(), nullable=True),
    sa.Column('validation_passed', sa.Integer(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('published_at', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('lab_charts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('chart_type', sa.String(), nullable=False),
    sa.Column('chart_data_json', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['lab_experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('metric_str', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['lab_experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('prev_snapshot_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('prev_rating', sa.String(), nullable=True),
    sa.Column('new_rating', sa.String(), nullable=True),
    sa.Column('composite_diff', sa.Float(), nullable=True),
    sa.Column('confidence_diff', sa.Float(), nullable=True),
    sa.Column('technical_diff', sa.Float(), nullable=True),
    sa.Column('ml_diff', sa.Float(), nullable=True),
    sa.Column('momentum_diff', sa.Float(), nullable=True),
    sa.Column('trend_diff', sa.Float(), nullable=True),
    sa.Column('risk_diff', sa.Float(), nullable=True),
    sa.Column('primary_driver', sa.String(), nullable=True),
    sa.Column('secondary_driver', sa.String(), nullable=True),
    sa.Column('is_significant', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_indicator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('ema_20', sa.Float(), nullable=True),
    sa.Column('ema_50', sa.Float(), nullable=True),
    sa.Column('ema_200', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('stoch_k', sa.Float(), nullable=True),
    sa.Column('adx_14', sa.Float(), nullable=True),
    sa.Column('obv', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('above_ema20', sa.Integer(), nullable=True),
    sa.Column('above_ema50', sa.Integer(), nullable=True),
    sa.Column('above_ema200', sa.Integer(), nullable=True),
    sa.Column('near_52w_high', sa.Integer(), nullable=True),
    sa.Column('near_52w_low', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'symbol', name='uq_snapshot_indicator_symbol')
    )
    op.create_table('snapshot_market',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('total_stocks', sa.Integer(), nullable=True),
    sa.Column('advancing_stocks', sa.Integer(), nullable=True),
    sa.Column('declining_stocks', sa.Integer(), nullable=True),
    sa.Column('unchanged_stocks', sa.Integer(), nullable=True),
    sa.Column('advance_decline_ratio', sa.Float(), nullable=True),
    sa.Column('advance_volume', sa.BigInteger(), nullable=True),
    sa.Column('decline_volume', sa.BigInteger(), nullable=True),
    sa.Column('stocks_above_ema20', sa.Integer(), nullable=True),
    sa.Column('stocks_above_ema50', sa.Integer(), nullable=True),
    sa.Column('stocks_above_ema200', sa.Integer(), nullable=True),
    sa.Column('pct_above_ema20', sa.Float(), nullable=True),
    sa.Column('pct_above_ema50', sa.Float(), nullable=True),
    sa.Column('pct_above_ema200', sa.Float(), nullable=True),
    sa.Column('week52_high_count', sa.Integer(), nullable=True),
    sa.Column('week52_low_count', sa.Integer(), nullable=True),
    sa.Column('avg_composite', sa.Float(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('avg_rsi', sa.Float(), nullable=True),
    sa.Column('avg_momentum', sa.Float(), nullable=True),
    sa.Column('avg_daily_chg_pct', sa.Float(), nullable=True),
    sa.Column('bullish_pct', sa.Float(), nullable=True),
    sa.Column('bearish_pct', sa.Float(), nullable=True),
    sa.Column('market_regime', sa.String(), nullable=True),
    sa.Column('strong_buy_count', sa.Integer(), nullable=True),
    sa.Column('buy_count', sa.Integer(), nullable=True),
    sa.Column('hold_count', sa.Integer(), nullable=True),
    sa.Column('sell_count', sa.Integer(), nullable=True),
    sa.Column('strong_sell_count', sa.Integer(), nullable=True),
    sa.Column('india_vix', sa.Float(), nullable=True),
    sa.Column('pcr', sa.Float(), nullable=True),
    sa.Column('fii_activity', sa.Float(), nullable=True),
    sa.Column('dii_activity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', name='uq_snapshot_market_snap')
    )
    op.create_table('snapshot_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('stage_status', sa.String(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('stocks_success', sa.Integer(), nullable=True),
    sa.Column('stocks_failed', sa.Integer(), nullable=True),
    sa.Column('warnings_count', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.Column('log_summary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('html_path', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('generated_at', sa.String(), nullable=True),
    sa.Column('file_size_kb', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('trend_component', sa.Float(), nullable=True),
    sa.Column('momentum_component', sa.Float(), nullable=True),
    sa.Column('volatility_component', sa.Float(), nullable=True),
    sa.Column('volume_component', sa.Float(), nullable=True),
    sa.Column('lgbm_signal', sa.Float(), nullable=True),
    sa.Column('rf_signal', sa.Float(), nullable=True),
    sa.Column('xgb_signal', sa.Float(), nullable=True),
    sa.Column('gru_hold', sa.Float(), nullable=True),
    sa.Column('gru_long', sa.Float(), nullable=True),
    sa.Column('gru_short', sa.Float(), nullable=True),
    sa.Column('return_score', sa.Float(), nullable=True),
    sa.Column('primary_driver', sa.String(), nullable=True),
    sa.Column('secondary_driver', sa.String(), nullable=True),
    sa.Column('w_technical', sa.Float(), nullable=True),
    sa.Column('w_ml', sa.Float(), nullable=True),
    sa.Column('w_gru', sa.Float(), nullable=True),
    sa.Column('w_reliability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'symbol', name='uq_snapshot_score_symbol')
    )
    op.create_table('snapshot_sector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('stock_count', sa.Integer(), nullable=True),
    sa.Column('avg_composite', sa.Float(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('avg_technical', sa.Float(), nullable=True),
    sa.Column('avg_momentum', sa.Float(), nullable=True),
    sa.Column('avg_trend', sa.Float(), nullable=True),
    sa.Column('avg_risk', sa.Float(), nullable=True),
    sa.Column('strong_buy_count', sa.Integer(), nullable=True),
    sa.Column('buy_count', sa.Integer(), nullable=True),
    sa.Column('hold_count', sa.Integer(), nullable=True),
    sa.Column('sell_count', sa.Integer(), nullable=True),
    sa.Column('strong_sell_count', sa.Integer(), nullable=True),
    sa.Column('bullish_pct', sa.Float(), nullable=True),
    sa.Column('bearish_pct', sa.Float(), nullable=True),
    sa.Column('sector_rank', sa.Integer(), nullable=True),
    sa.Column('top_stock', sa.String(), nullable=True),
    sa.Column('weakest_stock', sa.String(), nullable=True),
    sa.Column('avg_daily_chg_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'sector', name='uq_snapshot_sector_name')
    )
    op.create_table('snapshot_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('prev_close', sa.Float(), nullable=True),
    sa.Column('daily_chg_pct', sa.Float(), nullable=True),
    sa.Column('daily_chg_amt', sa.Float(), nullable=True),
    sa.Column('week52_high', sa.Float(), nullable=True),
    sa.Column('week52_low', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('gru_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('final_rating', sa.String(), nullable=True),
    sa.Column('portfolio_eligible', sa.Integer(), nullable=True),
    sa.Column('conviction_level', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('universe_position', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('download_status', sa.String(), nullable=True),
    sa.Column('data_warnings', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'symbol', name='uq_snapshot_stock_symbol')
    )
    op.create_table('snapshot_validation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('check_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('affected_count', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('watchlist_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('rank_in_list', sa.Integer(), nullable=True),
    sa.Column('score_used', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'watchlist_name', 'symbol', name='uq_snapshot_watchlist_entry')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot_watchlist')
    op.drop_table('snapshot_validation')
    op.drop_table('snapshot_stock')
    op.drop_table('snapshot_sector')
    op.drop_table('snapshot_score')
    op.drop_table('snapshot_report')
    op.drop_table('snapshot_metadata')
    op.drop_table('snapshot_market')
    op.drop_table('snapshot_indicator')
    op.drop_table('snapshot_change')
    op.drop_table('lab_metrics')
    op.drop_table('lab_charts')
    op.drop_table('snapshots')
    op.drop_table('security_master')
    op.drop_table('score_snapshot')
    op.drop_table('report_snapshot')
    op.drop_table('report_history')
    op.drop_table('my_stocks')
    op.drop_table('market_daily')
    op.drop_table('lab_weight_snapshots')
    op.drop_table('lab_reports')
    op.drop_table('lab_rec_audit')
    op.drop_table('lab_experiments')
    op.drop_table('lab_drift_alerts')
    op.drop_table('indicator_snapshot')
    op.drop_table('feature_snapshot')
    op.drop_table('explainability_snapshot')
    op.drop_table('analysis_history')
    # ### end Alembic commands ###
