"""add_pipeline_run_id

Revision ID: cc7962a16cae
Revises: 373203f01064
Create Date: 2026-07-14 11:51:06.181814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7962a16cae'
down_revision: Union[str, Sequence[str], None] = '373203f01064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshots', sa.Column('pipeline_run_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshots', 'pipeline_run_id')
    # ### end Alembic commands ###
